command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - $DATABRICKS_APP_PORT

env:
  - name: MAPBOX_TOKEN
    valueFrom: mapbox_token
  - name: DATABRICKS_AI_ENDPOINT
    valueFrom: ai_model
